# Generated by Django 5.2.7 on 2026-02-23 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False),
        ),
    ]
